In [3]:
from os import listdir
from os.path import isfile, join
import h5py
import cv2
import numpy as np
from skimage.util import view_as_blocks
from time import gmtime, strftime
from multiprocessing import Pool
from os import mkdir

In [2]:
#import matlab.engine
#eng = matlab.engine.start_matlab()

In [3]:
#file='/mnt/disk125/main/marmosetRIKEN/NZ/m919/m919F/M919XXL/M919-F78--_3_0234.jp2'
testfile='MATdata/M919-F78--_3_0234.mat'

In [18]:
data=h5py.File(testfile)
img=np.asarray(data['img'],'uint8')
img=img.T

In [ ]:
#

In [35]:
cv2.imwrite('testt.jp2',img[18000:22000,17000:21000,:])

True

In [69]:
sub=img[18000:22000,17000:21000,:]

In [70]:
sub=cv2.GaussianBlur(sub,(5,5),5)

In [38]:
cv2.imwrite('gau.jp2',sub)

True

In [82]:
sub=img[18000:22000,17000:21000,:]
Gmask= np.max(sub,axis=2) != sub[:,:,1]
sub[Gmask]=0
sub[sub[:,:,1]<50] =0
sub=cv2.cvtColor(sub,cv2.COLOR_BGR2GRAY)

In [83]:
cv2.imwrite('gau-gmask.jp2',sub)

True

In [73]:
sub[Gmask]=0
sub[sub[:,:,1]<20] =0

In [74]:
sub.shape

(4000, 4000, 3)

In [75]:
cv2.imwrite('gau-gmask.jp2',sub)

True

In [68]:
sum(sum(Gmask))

0

In [85]:
sub[0:512]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [87]:
k=img[0:512,0:512,:]

In [88]:
k.shape

(512, 512, 3)

In [90]:
max=48000
x=0
y=512
while (x+512<48000):
    print [x,y]
    x=y-10
    y=x+512

[0, 512]
[502, 1014]
[1004, 1516]
[1506, 2018]
[2008, 2520]
[2510, 3022]
[3012, 3524]
[3514, 4026]
[4016, 4528]
[4518, 5030]
[5020, 5532]
[5522, 6034]
[6024, 6536]
[6526, 7038]
[7028, 7540]
[7530, 8042]
[8032, 8544]
[8534, 9046]
[9036, 9548]
[9538, 10050]
[10040, 10552]
[10542, 11054]
[11044, 11556]
[11546, 12058]
[12048, 12560]
[12550, 13062]
[13052, 13564]
[13554, 14066]
[14056, 14568]
[14558, 15070]
[15060, 15572]
[15562, 16074]
[16064, 16576]
[16566, 17078]
[17068, 17580]
[17570, 18082]
[18072, 18584]
[18574, 19086]
[19076, 19588]
[19578, 20090]
[20080, 20592]
[20582, 21094]
[21084, 21596]
[21586, 22098]
[22088, 22600]
[22590, 23102]
[23092, 23604]
[23594, 24106]
[24096, 24608]
[24598, 25110]
[25100, 25612]
[25602, 26114]
[26104, 26616]
[26606, 27118]
[27108, 27620]
[27610, 28122]
[28112, 28624]
[28614, 29126]
[29116, 29628]
[29618, 30130]
[30120, 30632]
[30622, 31134]
[31124, 31636]
[31626, 32138]
[32128, 32640]
[32630, 33142]
[33132, 33644]
[33634, 34146]
[34136, 34648]
[34638, 3

In [1]:
def GetBlockList(overlap=10):
    x1=0
    y1=512
    blocklist=[]
    count = 0
    while (x1+512<36000):
        x2=0
        y2=512
        while (x2+512<48000):
            blocklist.append(np.asarray([x1,y1,x2,y2,count]))
            count = count + 1
            x2=y2-overlap
            y2=x2+512
        x1=y1-overlap
        y1=x1+512
    return blocklist

In [175]:
def GetCoord(data,overlap=10):
    x=(data[3]+2*overlap)/512-1
    y=(data[1]+2*overlap)/512-1
    return [x,y]

In [4]:
blocks=GetBlockList()

In [6]:
blocks[3549]

array([18574, 19086, 17068, 17580,  3549])

In [7]:
blocks

[array([  0, 512,   0, 512,   0]),
 array([   0,  512,  502, 1014,    1]),
 array([   0,  512, 1004, 1516,    2]),
 array([   0,  512, 1506, 2018,    3]),
 array([   0,  512, 2008, 2520,    4]),
 array([   0,  512, 2510, 3022,    5]),
 array([   0,  512, 3012, 3524,    6]),
 array([   0,  512, 3514, 4026,    7]),
 array([   0,  512, 4016, 4528,    8]),
 array([   0,  512, 4518, 5030,    9]),
 array([   0,  512, 5020, 5532,   10]),
 array([   0,  512, 5522, 6034,   11]),
 array([   0,  512, 6024, 6536,   12]),
 array([   0,  512, 6526, 7038,   13]),
 array([   0,  512, 7028, 7540,   14]),
 array([   0,  512, 7530, 8042,   15]),
 array([   0,  512, 8032, 8544,   16]),
 array([   0,  512, 8534, 9046,   17]),
 array([   0,  512, 9036, 9548,   18]),
 array([    0,   512,  9538, 10050,    19]),
 array([    0,   512, 10040, 10552,    20]),
 array([    0,   512, 10542, 11054,    21]),
 array([    0,   512, 11044, 11556,    22]),
 array([    0,   512, 11546, 12058,    23]),
 array([    0,   512

In [214]:
GetCoord(blocks[20])

[19, 0]

In [8]:
for i in blocks:
    print str(i[0])+' '+str(i[2])+' '+str(0)

0 0 0
0 502 0
0 1004 0
0 1506 0
0 2008 0
0 2510 0
0 3012 0
0 3514 0
0 4016 0
0 4518 0
0 5020 0
0 5522 0
0 6024 0
0 6526 0
0 7028 0
0 7530 0
0 8032 0
0 8534 0
0 9036 0
0 9538 0
0 10040 0
0 10542 0
0 11044 0
0 11546 0
0 12048 0
0 12550 0
0 13052 0
0 13554 0
0 14056 0
0 14558 0
0 15060 0
0 15562 0
0 16064 0
0 16566 0
0 17068 0
0 17570 0
0 18072 0
0 18574 0
0 19076 0
0 19578 0
0 20080 0
0 20582 0
0 21084 0
0 21586 0
0 22088 0
0 22590 0
0 23092 0
0 23594 0
0 24096 0
0 24598 0
0 25100 0
0 25602 0
0 26104 0
0 26606 0
0 27108 0
0 27610 0
0 28112 0
0 28614 0
0 29116 0
0 29618 0
0 30120 0
0 30622 0
0 31124 0
0 31626 0
0 32128 0
0 32630 0
0 33132 0
0 33634 0
0 34136 0
0 34638 0
0 35140 0
0 35642 0
0 36144 0
0 36646 0
0 37148 0
0 37650 0
0 38152 0
0 38654 0
0 39156 0
0 39658 0
0 40160 0
0 40662 0
0 41164 0
0 41666 0
0 42168 0
0 42670 0
0 43172 0
0 43674 0
0 44176 0
0 44678 0
0 45180 0
0 45682 0
0 46184 0
0 46686 0
0 47188 0
502 0 0
502 502 0
502 1004 0
502 1506 0
502 2008 0
502 2510 0
502 3012 0
5

In [215]:
dblocks[len(blocks)-1]

array([35140, 35652, 47188, 47700,  6744])

In [216]:
GetCoord(blocks[6744])

[92, 68]

In [217]:
blocks[6744]

array([35140, 35652, 47188, 47700,  6744])

In [218]:
Order2Cood(6744)

[94, 70]

In [229]:
#metadata info
for i in range(0,6745):
    k=Order2Cood(i)
    print str(k[1])+' '+str(k[0])+' '+ str(0)

0 0 0
0 1 0
0 2 0
0 3 0
0 4 0
0 5 0
0 6 0
0 7 0
0 8 0
0 9 0
0 10 0
0 11 0
0 12 0
0 13 0
0 14 0
0 15 0
0 16 0
0 17 0
0 18 0
0 19 0
0 20 0
0 21 0
0 22 0
0 23 0
0 24 0
0 25 0
0 26 0
0 27 0
0 28 0
0 29 0
0 30 0
0 31 0
0 32 0
0 33 0
0 34 0
0 35 0
0 36 0
0 37 0
0 38 0
0 39 0
0 40 0
0 41 0
0 42 0
0 43 0
0 44 0
0 45 0
0 46 0
0 47 0
0 48 0
0 49 0
0 50 0
0 51 0
0 52 0
0 53 0
0 54 0
0 55 0
0 56 0
0 57 0
0 58 0
0 59 0
0 60 0
0 61 0
0 62 0
0 63 0
0 64 0
0 65 0
0 66 0
0 67 0
0 68 0
0 69 0
0 70 0
0 71 0
0 72 0
0 73 0
0 74 0
0 75 0
0 76 0
0 77 0
0 78 0
0 79 0
0 80 0
0 81 0
0 82 0
0 83 0
0 84 0
0 85 0
0 86 0
0 87 0
0 88 0
0 89 0
0 90 0
0 91 0
0 92 0
0 93 0
0 94 0
1 0 0
1 1 0
1 2 0
1 3 0
1 4 0
1 5 0
1 6 0
1 7 0
1 8 0
1 9 0
1 10 0
1 11 0
1 12 0
1 13 0
1 14 0
1 15 0
1 16 0
1 17 0
1 18 0
1 19 0
1 20 0
1 21 0
1 22 0
1 23 0
1 24 0
1 25 0
1 26 0
1 27 0
1 28 0
1 29 0
1 30 0
1 31 0
1 32 0
1 33 0
1 34 0
1 35 0
1 36 0
1 37 0
1 38 0
1 39 0
1 40 0
1 41 0
1 42 0
1 43 0
1 44 0
1 45 0
1 46 0
1 47 0
1 48 0
1 49 0
1 50 

In [127]:
def Cood2Order(data):
    #assuming x is 0 to 92, y is 0 to 68
    return (data[1]) * 93 + data[0]
    #

In [227]:
def Order2Cood(a):
    #assuming x is 0 to 94, y is 0 to 70
    x=a%95
    y=(a-(a%95))/95
    return [x,y]

In [134]:
Cood2Order([92,68])

6416

In [139]:
38162 % 512 -512

-238

In [149]:
Order2Cood(6744)

[94, 70]

In [150]:
ls

cvt2.m  cvt4.m  Data-pipline.ipynb  gau-gmask.jp2  MATdata/  testt.jp2
cvt3.m  cvt.m   filelist.txt        gau.jp2        test.jp2


In [151]:
pwd

u'/home/xli/Documents/Marmo919_SK'

In [157]:
for i in range(0,6745):
    mkdir(str(i))

In [199]:
def blockprocess(img,metadata,filecount):
    print type(metadata)
    sub=img[metadata[0]:metadata[1],metadata[2]:metadata[3],:]
    Gmask= np.max(sub,axis=2) != sub[:,:,1]
    sub[Gmask]=0
    sub[sub[:,:,1]<50] =0
    sub=cv2.cvtColor(sub,cv2.COLOR_BGR2GRAY)
    cv2.imwrite(str(metadata[4])+'/'+str(filecount)+'.jp2',sub)

In [200]:
blockprocess(img,(blocks[0]),0)

<type 'numpy.ndarray'>


In [187]:
type(blocks[0])

numpy.ndarray

In [164]:
type(img)

numpy.ndarray

In [165]:
img.shape

(36000, 48000, 3)

In [211]:
count=0
with open('MATdata/orderfile.txt') as f:
    content = f.readlines()
# you may also want to remove whitespace characters like `\n` at the end of each line
content = [x.strip() for x in content]     
para=[]
for i in content:
    para.append(('MATdata/'+i,count))
    count = count + 1

In [212]:
para

[('MATdata/M919-F5--_2_0014.mat', 0),
 ('MATdata/M919-F5--_3_0015.mat', 1),
 ('MATdata/M919-F6--_2_0017.mat', 2),
 ('MATdata/M919-F6--_3_0018.mat', 3),
 ('MATdata/M919-F7--_2_0020.mat', 4),
 ('MATdata/M919-F7--_3_0021.mat', 5),
 ('MATdata/M919-F8--_2_0023.mat', 6),
 ('MATdata/M919-F8--_3_0024.mat', 7),
 ('MATdata/M919-F9--_2_0026.mat', 8),
 ('MATdata/M919-F9--_3_0027.mat', 9),
 ('MATdata/M919-F10--_2_0029.mat', 10),
 ('MATdata/M919-F10--_3_0030.mat', 11),
 ('MATdata/M919-F11--_2_0032.mat', 12),
 ('MATdata/M919-F11--_3_0033.mat', 13),
 ('MATdata/M919-F12--_2_0035.mat', 14),
 ('MATdata/M919-F12--_3_0036.mat', 15),
 ('MATdata/M919-F13--_2_0038.mat', 16),
 ('MATdata/M919-F13--_3_0039.mat', 17),
 ('MATdata/M919-F14--_2_0041.mat', 18),
 ('MATdata/M919-F14--_3_0042.mat', 19),
 ('MATdata/M919-F15--_2_0044.mat', 20),
 ('MATdata/M919-F15--_3_0045.mat', 21),
 ('MATdata/M919-F16--_2_0047.mat', 22),
 ('MATdata/M919-F16--_3_0048.mat', 23),
 ('MATdata/M919-F17--_2_0050.mat', 24),
 ('MATdata/M919-F17-